# Publish GitHub workflow artifacts
name: Publish GitHub Actions Artifacts

on:
  push:
    branches: [main]

jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads

      - name: Step 2 - Add artifacts to publish to the temp folder
        run: |
            cd downloads
            ./config/
            models/
            ./main.py
            cd ..

      - name: Step 3 - Use the upload Artifact github action
        uses: actions/upload-artifact@v3
        with:
          name: movie-api
          path: downloads